export const projects = [
  {
    id: 1,
    name: "Dachi V Gorax",
    codeUrl: "",
    websiteUrl: "https://dachivgorax.uz/",
    technology: "ReactJS, Bootstrap, TanStack Query",
    image: "/dachi.png",
  },
  {
    id: 2,
    name: "Gym App",
    codeUrl: "https://github.com/developerdiyorbek/Gym-Project",
    websiteUrl: "https://gym-project-24f84.web.app/",
    technology: "ReactJS, Shadcn UI, Firebase",
    image: "/gym.png",
  },
  {
    id: 8,
    name: "Blogs",
    codeUrl: "https://github.com/developerdiyorbek/diyor-blog",
    websiteUrl: "https://www.dili017.uz/",
    technology: "NextJS, Graphql, Typescript",
    image: "/blog.png",
  },
  {
    id: 3,
    name: "Gmt Website",
    codeUrl: "https://github.com/developerdiyorbek/GMT-project",
    websiteUrl: "https://gmt-project-ehrf.vercel.app/",
    technology: "ReactJS, TailwindCSS",
    image: "/gmt.png",
  },
  {
    id: 4,
    name: "Myshop Website",
    codeUrl: "https://github.com/developerdiyorbek/My-shop",
    websiteUrl: "https://my-shop-five-brown.vercel.app",
    technology: "NextJS, TailwindCSS, Typescript",
    image: "/myshop.png",
  },
  {
    id: 6,
    name: "Todo App",
    codeUrl: "https://github.com/developerdiyorbek/Todo-App",
    websiteUrl: "https://todo-app-tqsr.vercel.app/",
    technology: "NextJs, MUI, TanStack Query",
    image: "/todo.png",
  },
  {
    id: 5,
    name: "Input validation",
    codeUrl: "https://github.com/developerdiyorbek/Input-Validation",
    websiteUrl: "https://input-validation2.vercel.app/",
    technology: "ReactJS, TailwindCSS, CleaveJs",
    image: "/validation.png",
  },

  {
    id: 7,
    name: "Pig Game",
    codeUrl: "https://github.com/developerdiyorbek/Pig-Game",
    websiteUrl: "https://pig-game-alpha-two.vercel.app/",
    technology: "HTML, CSS, Javascript",
    image: "/pigGame.png",
  },
];
