export const projects = [
  {
    id: 1,
    name: "Diyordemy",
    codeUrl: "",
    websiteUrl: "https://diyordemy.uz/",
    technology: "NextJS, MongoDB, Stripe",
    image: "/diyordemy.png",
  },
  {
    id: 2,
    name: "Myshop Website",
    codeUrl: "https://github.com/developerdiyorbek/E-Commerce",
    websiteUrl: "https://e-commerce-ashy-beta-75.vercel.app/",
    technology: "NextJS, Formik, React-Query",
    image: "/myshop.png",
  },
  {
    id: 3,
    name: "Blogs",
    codeUrl: "https://github.com/developerdiyorbek/diyor-blog",
    websiteUrl: "https://www.dili017.uz/",
    technology: "NextJS, Graphql, Typescript",
    image: "/blog.png",
  },

  {
    id: 4,
    name: "Input validation",
    codeUrl: "https://github.com/developerdiyorbek/InputValidation",
    websiteUrl: "https://input-validation-nltu.vercel.app/en",
    technology: "NextJS, Shadcn UI, Formik",
    image: "/validation2.png",
  },
  {
    id: 5,
    name: "Gmt Website",
    codeUrl: "https://github.com/developerdiyorbek/GMT-project",
    websiteUrl: "https://gmt-project-ehrf.vercel.app/",
    technology: "ReactJS, TailwindCSS",
    image: "/gmt.png",
  },
  {
    id: 6,
    name: "Gym App",
    codeUrl: "https://github.com/developerdiyorbek/Gym-Project",
    websiteUrl: "https://gym-project-24f84.web.app/",
    technology: "ReactJS, Shadcn UI, Firebase",
    image: "/gym.png",
  },
  {
    id: 7,
    name: "Map of Uzbekistan",
    codeUrl: "https://github.com/developerdiyorbek/Map-of-Uzbekistan",
    websiteUrl: "https://map-of-uzbekistan.vercel.app/",
    technology: "ReactJS,  react-i18n, typescript",
    image: "/uzbekistanmap.png",
  },
  {
    id: 8,
    name: "Full Stack Todo App",
    codeUrl: "https://github.com/developerdiyorbek/Full-Stack-Todo-App",
    websiteUrl: "https://full-stack-todo-app-mu.vercel.app",
    technology: "Next JS, MongoDB, Shadcn UI, PWA",
    image: "/fullStackTodo.png",
  },
  {
    id: 9,
    name: "Input Steps",
    codeUrl: "https://github.com/developerdiyorbek/Input-Validation",
    websiteUrl: "https://input-validation2.vercel.app/",
    technology: "ReactJS, TailwindCSS, CleaveJs",
    image: "/validation.png",
  },

  {
    id: 10,
    name: "Rest countries",
    codeUrl: "https://github.com/developerdiyorbek/Rest-Countries",
    websiteUrl: "https://rest-countries2.vercel.app/",
    technology: "ReactJS, TailwindCSS, React-router-dom",
    image: "/restCountries.png",
  },

  {
    id: 11,
    name: "Pig Game",
    codeUrl: "https://github.com/developerdiyorbek/Pig-Game",
    websiteUrl: "https://pig-game-alpha-two.vercel.app/",
    technology: "HTML, CSS, Javascript",
    image: "/pigGame.png",
  },
];
